import { invoke } from "@tauri-apps/api/core";
import type {
  AppConfig,
  LogEntry,
  MonitorInfo,
  RestoreResult,
  WindowAutoLayoutConfig,
  WindowInfo,
} from "./types";

export const isTauriRuntime = typeof window !== "undefined" && "__TAURI_INTERNALS__" in window;

const browserConfig: WindowAutoLayoutConfig = {
  schemaVersion: 2,
  appVersion: "0.1.5",
  global: {
    defaultMonitorId: "display-2",
    monitorMissingBehavior: "doNothing",
    warnWhenMonitorMissing: true,
    advancedMode: false,
  },
  startup: {
    enabled: false,
    startMinimizedToTray: true,
    defaultProfileId: "profile-streaming",
    delaySeconds: 8,
    restoreOnLaunch: true,
    launchMissingApps: true,
    enforceAfterStartup: true,
  },
  tray: { minimizeToTrayOnClose: true, showRestoreStatus: true },
  hotkey: { enabled: true, accelerator: "Ctrl+Alt+L", restoreWithoutOpening: true },
  enforcement: { enabled: false, durationSeconds: 30, intervalMs: 1000 },
  profiles: [
    {
      id: "profile-streaming",
      name: "Streaming",
      description: "OBS and Discord arranged on the side monitor.",
      targetMonitorId: "display-2",
      startupRestore: true,
      enforceAfterRestore: true,
      apps: [
        {
          id: "app-obs",
          displayName: "OBS Studio",
          executablePath: null,
          arguments: [],
          workingDirectory: null,
          processName: "obs64.exe",
          titleRule: { mode: "startsWith", value: "OBS", caseSensitive: false },
          className: null,
          targetMonitorId: null,
          layout: { x: 0, y: 0, width: 1280, height: 720 },
          windowState: "normal",
          launchDelaySeconds: 0,
          detectionTimeoutSeconds: 25,
          retryIntervalMs: 700,
          launchIfMissing: true,
          moveIfRunning: true,
          forceResize: true,
          applyToAllMatchingWindows: false,
          restoreIfMinimized: true,
          pullHiddenWindows: true,
          wakeRunningProcess: true,
          allowEmptyTitle: false,
          notes: "",
        },
        {
          id: "app-discord",
          displayName: "Discord",
          executablePath: null,
          arguments: [],
          workingDirectory: null,
          processName: "Discord.exe",
          titleRule: null,
          className: null,
          targetMonitorId: null,
          layout: { x: 1280, y: 0, width: 640, height: 720 },
          windowState: "normal",
          launchDelaySeconds: 0,
          detectionTimeoutSeconds: 25,
          retryIntervalMs: 700,
          launchIfMissing: true,
          moveIfRunning: true,
          forceResize: true,
          applyToAllMatchingWindows: false,
          restoreIfMinimized: true,
          pullHiddenWindows: true,
          wakeRunningProcess: true,
          allowEmptyTitle: false,
          notes: "",
        },
        {
          id: "app-github-desktop",
          displayName: "GitHub Desktop",
          executablePath: null,
          arguments: [],
          workingDirectory: null,
          processName: "GitHubDesktop.exe",
          titleRule: { mode: "contains", value: "GitHub Desktop", caseSensitive: false },
          className: null,
          targetMonitorId: null,
          layout: { x: 80, y: 80, width: 1280, height: 900 },
          windowState: "normal",
          launchDelaySeconds: 0,
          detectionTimeoutSeconds: 45,
          retryIntervalMs: 700,
          launchIfMissing: true,
          moveIfRunning: true,
          forceResize: true,
          applyToAllMatchingWindows: false,
          restoreIfMinimized: true,
          pullHiddenWindows: true,
          wakeRunningProcess: true,
          allowEmptyTitle: false,
          notes: "",
        },
      ],
    },
  ],
};

const browserMonitors: MonitorInfo[] = [
  {
    id: "display-1",
    name: "\\\\.\\DISPLAY1",
    deviceName: "\\\\.\\DISPLAY1",
    x: 0,
    y: 0,
    width: 2560,
    height: 1440,
    workX: 0,
    workY: 0,
    workWidth: 2560,
    workHeight: 1392,
    scaleFactor: 1.25,
    isPrimary: true,
  },
  {
    id: "display-2",
    name: "\\\\.\\DISPLAY2",
    deviceName: "\\\\.\\DISPLAY2",
    x: -1920,
    y: 160,
    width: 1920,
    height: 1080,
    workX: -1920,
    workY: 160,
    workWidth: 1920,
    workHeight: 1040,
    scaleFactor: 1,
    isPrimary: false,
  },
];

const browserWindows: WindowInfo[] = [
  {
    handle: "0x001",
    title: "OBS Studio",
    className: "Qt672QWindowIcon",
    processId: 1200,
    processName: "obs64.exe",
    executablePath: "C:\\Program Files\\obs-studio\\bin\\64bit\\obs64.exe",
    monitorId: "display-2",
    x: -1920,
    y: 160,
    width: 1280,
    height: 720,
    isVisible: false,
    isMinimized: false,
  },
  {
    handle: "0x003",
    title: "GitHub Desktop",
    className: "Chrome_WidgetWin_1",
    processId: 1420,
    processName: "GitHubDesktop.exe",
    executablePath: "C:\\Users\\Rique\\AppData\\Local\\GitHubDesktop\\GitHubDesktop.exe",
    monitorId: "display-2",
    x: -1840,
    y: 240,
    width: 1280,
    height: 900,
    isVisible: true,
    isMinimized: false,
  },
  {
    handle: "0x002",
    title: "Discord",
    className: "Chrome_WidgetWin_1",
    processId: 1312,
    processName: "Discord.exe",
    executablePath: "C:\\Users\\Rique\\AppData\\Local\\Discord\\app\\Discord.exe",
    monitorId: "display-2",
    x: -640,
    y: 160,
    width: 640,
    height: 720,
    isVisible: true,
    isMinimized: false,
  },
];

const realApi = {
  getConfig: () => invoke<WindowAutoLayoutConfig>("get_config"),
  saveConfig: (nextConfig: WindowAutoLayoutConfig) =>
    invoke<WindowAutoLayoutConfig>("save_config", { nextConfig }),
  validateConfig: () => invoke<string[]>("validate_current_config"),
  presets: () => invoke<AppConfig[]>("get_app_presets"),
  monitors: () => invoke<MonitorInfo[]>("list_monitors"),
  windows: () => invoke<WindowInfo[]>("list_windows"),
  restoreProfile: (profileId?: string, launchMissing?: boolean) =>
    invoke<RestoreResult>("restore_profile", { profileId, launchMissing }),
  lockLayout: (profileId: string | undefined, durationSeconds: number) =>
    invoke<RestoreResult>("lock_layout_temporarily", { profileId, durationSeconds }),
  saveWindowLayout: (profileId: string, appId: string, windowHandle: string) =>
    invoke<WindowAutoLayoutConfig>("save_window_layout", { profileId, appId, windowHandle }),
  saveAllCurrentLayouts: (profileId: string) =>
    invoke<WindowAutoLayoutConfig>("save_all_current_layouts", { profileId }),
  logs: (maxLines = 500) => invoke<LogEntry[]>("read_logs", { maxLines }),
  clearLogs: () => invoke<void>("clear_logs"),
  setStartupEnabled: (enabled: boolean) =>
    invoke<WindowAutoLayoutConfig>("set_startup_enabled", { enabled }),
  startupEnabled: () => invoke<boolean>("startup_enabled"),
  configPath: () => invoke<string>("config_path"),
  logPath: () => invoke<string>("log_path"),
  openLogFile: () => invoke<void>("open_log_file"),
  showMainWindow: () => invoke<void>("show_main_window"),
};

const browserApi = {
  getConfig: async () => browserConfig,
  saveConfig: async (nextConfig: WindowAutoLayoutConfig) => nextConfig,
  validateConfig: async () => [],
  presets: async () => browserConfig.profiles[0].apps,
  monitors: async () => browserMonitors,
  windows: async () => browserWindows,
  restoreProfile: async (profileId?: string): Promise<RestoreResult> => ({
    profileId: profileId ?? "profile-streaming",
    profileName: "Streaming",
    status: "success",
    startedAt: new Date().toISOString(),
    finishedAt: new Date().toISOString(),
    monitor: browserMonitors[1],
    results: browserConfig.profiles[0].apps.map((app) => ({
      appId: app.id,
      displayName: app.displayName,
      status: "success",
      message: "Applied layout",
      matchedWindows: browserWindows.filter((window) => window.processName === app.processName),
    })),
  }),
  lockLayout: async (profileId?: string) => browserApi.restoreProfile(profileId),
  saveWindowLayout: async () => browserConfig,
  saveAllCurrentLayouts: async () => browserConfig,
  logs: async (): Promise<LogEntry[]> => [
    {
      timestamp: new Date().toISOString(),
      severity: "info",
      profile: "Streaming",
      app: "OBS Studio",
      message: "Applied layout to 1 window",
    },
  ],
  clearLogs: async () => undefined,
  setStartupEnabled: async (enabled: boolean) => ({
    ...browserConfig,
    startup: { ...browserConfig.startup, enabled },
  }),
  startupEnabled: async () => false,
  configPath: async () => "C:\\Users\\Rique\\AppData\\Roaming\\com.rique.windowautolayout\\config.json",
  logPath: async () => "C:\\Users\\Rique\\AppData\\Roaming\\com.rique.windowautolayout\\logs\\windowautolayout.log",
  openLogFile: async () => undefined,
  showMainWindow: async () => undefined,
};

export const api = isTauriRuntime ? realApi : browserApi;
